version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:db
    ports:
      - 8001:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${MYSQL_PASSWORD:-prestashop}
      DB_NAME: ${MYSQL_DATABASE:-prestashop}
      DB_SERVER: ${MYSQL_SERVER:-mysql}
      DB_PREFIX: ${MYSQL_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:8000}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-fr}
      PS_LANGUAGE: ${PS_LANGUAGE:-fr}
      PS_DEV_MODE: ${PS_DEV_MODE:-0}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated